# GoReleaser config for portctl
# SLSA, SBOM, Homebrew, Changelog, Multi-platform, Signed, Audit
version: 2
project_name: portctl
builds:
  - id: portctl
    main: ./cmd/portctl
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w -X dagger/portctl/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    ids: [portctl]
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md
      - .well-known/**
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign-blob
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - ${artifact}
      - --yes
    artifacts: all
    
sboms:
  - id: spdx
    artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.spdx.json"
  - id: cyclonedx
    artifacts: archive
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "cyclonedx-json={{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.cyclonedx.json"
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.cyclonedx.json"
      
brews:
  - name: portctl
    repository:
      owner: ckodex-labs
      name: homebrew-tap
    description: Secure, cross-platform CLI for managing processes on ports.
    homepage: https://github.com/ckodex-labs/portctl
    install: |
      bin.install "portctl"

release:
  github:
    owner: ckodex-labs
    name: portctl
  draft: false
  prerelease: auto
