// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/portctl.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortctlService_ListProcesses_FullMethodName  = "/portctl.PortctlService/ListProcesses"
	PortctlService_KillProcess_FullMethodName    = "/portctl.PortctlService/KillProcess"
	PortctlService_ScanPorts_FullMethodName      = "/portctl.PortctlService/ScanPorts"
	PortctlService_GetSystemStats_FullMethodName = "/portctl.PortctlService/GetSystemStats"
	PortctlService_GetStatus_FullMethodName      = "/portctl.PortctlService/GetStatus"
)

// PortctlServiceClient is the client API for PortctlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PortctlService provides gRPC API for port and process management
type PortctlServiceClient interface {
	// List running processes, optionally filtered by port or service
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	// Kill a process by PID or port
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error)
	// Scan ports on a host
	ScanPorts(ctx context.Context, in *ScanPortsRequest, opts ...grpc.CallOption) (*ScanPortsResponse, error)
	// Get system resource statistics
	GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error)
	// Get server status and version
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type portctlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortctlServiceClient(cc grpc.ClientConnInterface) PortctlServiceClient {
	return &portctlServiceClient{cc}
}

func (c *portctlServiceClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, PortctlService_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portctlServiceClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillProcessResponse)
	err := c.cc.Invoke(ctx, PortctlService_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portctlServiceClient) ScanPorts(ctx context.Context, in *ScanPortsRequest, opts ...grpc.CallOption) (*ScanPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanPortsResponse)
	err := c.cc.Invoke(ctx, PortctlService_ScanPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portctlServiceClient) GetSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, PortctlService_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portctlServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PortctlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortctlServiceServer is the server API for PortctlService service.
// All implementations must embed UnimplementedPortctlServiceServer
// for forward compatibility.
//
// PortctlService provides gRPC API for port and process management
type PortctlServiceServer interface {
	// List running processes, optionally filtered by port or service
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	// Kill a process by PID or port
	KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error)
	// Scan ports on a host
	ScanPorts(context.Context, *ScanPortsRequest) (*ScanPortsResponse, error)
	// Get system resource statistics
	GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error)
	// Get server status and version
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedPortctlServiceServer()
}

// UnimplementedPortctlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortctlServiceServer struct{}

func (UnimplementedPortctlServiceServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedPortctlServiceServer) KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedPortctlServiceServer) ScanPorts(context.Context, *ScanPortsRequest) (*ScanPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanPorts not implemented")
}
func (UnimplementedPortctlServiceServer) GetSystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedPortctlServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPortctlServiceServer) mustEmbedUnimplementedPortctlServiceServer() {}
func (UnimplementedPortctlServiceServer) testEmbeddedByValue()                        {}

// UnsafePortctlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortctlServiceServer will
// result in compilation errors.
type UnsafePortctlServiceServer interface {
	mustEmbedUnimplementedPortctlServiceServer()
}

func RegisterPortctlServiceServer(s grpc.ServiceRegistrar, srv PortctlServiceServer) {
	// If the following call pancis, it indicates UnimplementedPortctlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortctlService_ServiceDesc, srv)
}

func _PortctlService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortctlServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortctlService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortctlServiceServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortctlService_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortctlServiceServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortctlService_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortctlServiceServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortctlService_ScanPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortctlServiceServer).ScanPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortctlService_ScanPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortctlServiceServer).ScanPorts(ctx, req.(*ScanPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortctlService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortctlServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortctlService_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortctlServiceServer).GetSystemStats(ctx, req.(*SystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortctlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortctlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortctlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortctlServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortctlService_ServiceDesc is the grpc.ServiceDesc for PortctlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortctlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portctl.PortctlService",
	HandlerType: (*PortctlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProcesses",
			Handler:    _PortctlService_ListProcesses_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _PortctlService_KillProcess_Handler,
		},
		{
			MethodName: "ScanPorts",
			Handler:    _PortctlService_ScanPorts_Handler,
		},
		{
			MethodName: "GetSystemStats",
			Handler:    _PortctlService_GetSystemStats_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PortctlService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/portctl.proto",
}
