// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/portctl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list processes
type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          *int32                 `protobuf:"varint,1,opt,name=port,proto3,oneof" json:"port,omitempty"`      // Filter by specific port
	Service       *string                `protobuf:"bytes,2,opt,name=service,proto3,oneof" json:"service,omitempty"` // Filter by service name
	User          *string                `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`       // Filter by user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_proto_portctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{0}
}

func (x *ListProcessesRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *ListProcessesRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListProcessesRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

// A single process
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ServiceType   string                 `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryMb      float64                `protobuf:"fixed64,7,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	StartTime     int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_proto_portctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{1}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Process) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Process) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Process) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Process) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// Response with list of processes
type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_proto_portctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{2}
}

func (x *ListProcessesResponse) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Request to kill a process
type KillProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*KillProcessRequest_Pid
	//	*KillProcessRequest_Port
	Target        isKillProcessRequest_Target `protobuf_oneof:"target"`
	Force         bool                        `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"` // Use SIGKILL instead of SIGTERM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_proto_portctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{3}
}

func (x *KillProcessRequest) GetTarget() isKillProcessRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *KillProcessRequest) GetPid() int32 {
	if x != nil {
		if x, ok := x.Target.(*KillProcessRequest_Pid); ok {
			return x.Pid
		}
	}
	return 0
}

func (x *KillProcessRequest) GetPort() int32 {
	if x != nil {
		if x, ok := x.Target.(*KillProcessRequest_Port); ok {
			return x.Port
		}
	}
	return 0
}

func (x *KillProcessRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type isKillProcessRequest_Target interface {
	isKillProcessRequest_Target()
}

type KillProcessRequest_Pid struct {
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3,oneof"`
}

type KillProcessRequest_Port struct {
	Port int32 `protobuf:"varint,2,opt,name=port,proto3,oneof"`
}

func (*KillProcessRequest_Pid) isKillProcessRequest_Target() {}

func (*KillProcessRequest_Port) isKillProcessRequest_Target() {}

// Response from kill operation
type KillProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KilledCount   int32                  `protobuf:"varint,3,opt,name=killed_count,json=killedCount,proto3" json:"killed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_proto_portctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{4}
}

func (x *KillProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KillProcessResponse) GetKilledCount() int32 {
	if x != nil {
		return x.KilledCount
	}
	return 0
}

// Request to scan ports
type ScanPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	StartPort     int32                  `protobuf:"varint,2,opt,name=start_port,json=startPort,proto3" json:"start_port,omitempty"`
	EndPort       int32                  `protobuf:"varint,3,opt,name=end_port,json=endPort,proto3" json:"end_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPortsRequest) Reset() {
	*x = ScanPortsRequest{}
	mi := &file_proto_portctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPortsRequest) ProtoMessage() {}

func (x *ScanPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPortsRequest.ProtoReflect.Descriptor instead.
func (*ScanPortsRequest) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{5}
}

func (x *ScanPortsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ScanPortsRequest) GetStartPort() int32 {
	if x != nil {
		return x.StartPort
	}
	return 0
}

func (x *ScanPortsRequest) GetEndPort() int32 {
	if x != nil {
		return x.EndPort
	}
	return 0
}

// Result of a single port scan
type PortScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "open", "closed", "filtered"
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortScanResult) Reset() {
	*x = PortScanResult{}
	mi := &file_proto_portctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortScanResult) ProtoMessage() {}

func (x *PortScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortScanResult.ProtoReflect.Descriptor instead.
func (*PortScanResult) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{6}
}

func (x *PortScanResult) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortScanResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PortScanResult) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Response with scan results
type ScanPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PortScanResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPortsResponse) Reset() {
	*x = ScanPortsResponse{}
	mi := &file_proto_portctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPortsResponse) ProtoMessage() {}

func (x *ScanPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPortsResponse.ProtoReflect.Descriptor instead.
func (*ScanPortsResponse) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{7}
}

func (x *ScanPortsResponse) GetResults() []*PortScanResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// Request for system stats
type SystemStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatsRequest) Reset() {
	*x = SystemStatsRequest{}
	mi := &file_proto_portctl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsRequest) ProtoMessage() {}

func (x *SystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{8}
}

// System statistics
type SystemStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent  float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	TotalProcesses int32                  `protobuf:"varint,3,opt,name=total_processes,json=totalProcesses,proto3" json:"total_processes,omitempty"`
	ListeningPorts int32                  `protobuf:"varint,4,opt,name=listening_ports,json=listeningPorts,proto3" json:"listening_ports,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_proto_portctl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{9}
}

func (x *SystemStatsResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemStatsResponse) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemStatsResponse) GetTotalProcesses() int32 {
	if x != nil {
		return x.TotalProcesses
	}
	return 0
}

func (x *SystemStatsResponse) GetListeningPorts() int32 {
	if x != nil {
		return x.ListeningPorts
	}
	return 0
}

// Request for server status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_portctl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{10}
}

// Server status
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ServerType    string                 `protobuf:"bytes,3,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"` // "grpc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_portctl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_portctl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_portctl_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

var File_proto_portctl_proto protoreflect.FileDescriptor

const file_proto_portctl_proto_rawDesc = "" +
	"\n" +
	"\x13proto/portctl.proto\x12\aportctl\"\x85\x01\n" +
	"\x14ListProcessesRequest\x12\x17\n" +
	"\x04port\x18\x01 \x01(\x05H\x00R\x04port\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x02 \x01(\tH\x01R\aservice\x88\x01\x01\x12\x17\n" +
	"\x04user\x18\x03 \x01(\tH\x02R\x04user\x88\x01\x01B\a\n" +
	"\x05_portB\n" +
	"\n" +
	"\b_serviceB\a\n" +
	"\x05_user\"\xdd\x01\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_mb\x18\a \x01(\x01R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\"G\n" +
	"\x15ListProcessesResponse\x12.\n" +
	"\tprocesses\x18\x01 \x03(\v2\x10.portctl.ProcessR\tprocesses\"^\n" +
	"\x12KillProcessRequest\x12\x12\n" +
	"\x03pid\x18\x01 \x01(\x05H\x00R\x03pid\x12\x14\n" +
	"\x04port\x18\x02 \x01(\x05H\x00R\x04port\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05forceB\b\n" +
	"\x06target\"l\n" +
	"\x13KillProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fkilled_count\x18\x03 \x01(\x05R\vkilledCount\"`\n" +
	"\x10ScanPortsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"start_port\x18\x02 \x01(\x05R\tstartPort\x12\x19\n" +
	"\bend_port\x18\x03 \x01(\x05R\aendPort\"V\n" +
	"\x0ePortScanResult\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\"F\n" +
	"\x11ScanPortsResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.portctl.PortScanResultR\aresults\"\x14\n" +
	"\x12SystemStatsRequest\"\xaf\x01\n" +
	"\x13SystemStatsResponse\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12'\n" +
	"\x0ftotal_processes\x18\x03 \x01(\x05R\x0etotalProcesses\x12'\n" +
	"\x0flistening_ports\x18\x04 \x01(\x05R\x0elisteningPorts\"\x0f\n" +
	"\rStatusRequest\"r\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vserver_type\x18\x03 \x01(\tR\n" +
	"serverType2\xf9\x02\n" +
	"\x0ePortctlService\x12N\n" +
	"\rListProcesses\x12\x1d.portctl.ListProcessesRequest\x1a\x1e.portctl.ListProcessesResponse\x12H\n" +
	"\vKillProcess\x12\x1b.portctl.KillProcessRequest\x1a\x1c.portctl.KillProcessResponse\x12B\n" +
	"\tScanPorts\x12\x19.portctl.ScanPortsRequest\x1a\x1a.portctl.ScanPortsResponse\x12K\n" +
	"\x0eGetSystemStats\x12\x1b.portctl.SystemStatsRequest\x1a\x1c.portctl.SystemStatsResponse\x12<\n" +
	"\tGetStatus\x12\x16.portctl.StatusRequest\x1a\x17.portctl.StatusResponseB\x16Z\x14dagger/portctl/protob\x06proto3"

var (
	file_proto_portctl_proto_rawDescOnce sync.Once
	file_proto_portctl_proto_rawDescData []byte
)

func file_proto_portctl_proto_rawDescGZIP() []byte {
	file_proto_portctl_proto_rawDescOnce.Do(func() {
		file_proto_portctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_portctl_proto_rawDesc), len(file_proto_portctl_proto_rawDesc)))
	})
	return file_proto_portctl_proto_rawDescData
}

var file_proto_portctl_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_portctl_proto_goTypes = []any{
	(*ListProcessesRequest)(nil),  // 0: portctl.ListProcessesRequest
	(*Process)(nil),               // 1: portctl.Process
	(*ListProcessesResponse)(nil), // 2: portctl.ListProcessesResponse
	(*KillProcessRequest)(nil),    // 3: portctl.KillProcessRequest
	(*KillProcessResponse)(nil),   // 4: portctl.KillProcessResponse
	(*ScanPortsRequest)(nil),      // 5: portctl.ScanPortsRequest
	(*PortScanResult)(nil),        // 6: portctl.PortScanResult
	(*ScanPortsResponse)(nil),     // 7: portctl.ScanPortsResponse
	(*SystemStatsRequest)(nil),    // 8: portctl.SystemStatsRequest
	(*SystemStatsResponse)(nil),   // 9: portctl.SystemStatsResponse
	(*StatusRequest)(nil),         // 10: portctl.StatusRequest
	(*StatusResponse)(nil),        // 11: portctl.StatusResponse
}
var file_proto_portctl_proto_depIdxs = []int32{
	1,  // 0: portctl.ListProcessesResponse.processes:type_name -> portctl.Process
	6,  // 1: portctl.ScanPortsResponse.results:type_name -> portctl.PortScanResult
	0,  // 2: portctl.PortctlService.ListProcesses:input_type -> portctl.ListProcessesRequest
	3,  // 3: portctl.PortctlService.KillProcess:input_type -> portctl.KillProcessRequest
	5,  // 4: portctl.PortctlService.ScanPorts:input_type -> portctl.ScanPortsRequest
	8,  // 5: portctl.PortctlService.GetSystemStats:input_type -> portctl.SystemStatsRequest
	10, // 6: portctl.PortctlService.GetStatus:input_type -> portctl.StatusRequest
	2,  // 7: portctl.PortctlService.ListProcesses:output_type -> portctl.ListProcessesResponse
	4,  // 8: portctl.PortctlService.KillProcess:output_type -> portctl.KillProcessResponse
	7,  // 9: portctl.PortctlService.ScanPorts:output_type -> portctl.ScanPortsResponse
	9,  // 10: portctl.PortctlService.GetSystemStats:output_type -> portctl.SystemStatsResponse
	11, // 11: portctl.PortctlService.GetStatus:output_type -> portctl.StatusResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_portctl_proto_init() }
func file_proto_portctl_proto_init() {
	if File_proto_portctl_proto != nil {
		return
	}
	file_proto_portctl_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_portctl_proto_msgTypes[3].OneofWrappers = []any{
		(*KillProcessRequest_Pid)(nil),
		(*KillProcessRequest_Port)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_portctl_proto_rawDesc), len(file_proto_portctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_portctl_proto_goTypes,
		DependencyIndexes: file_proto_portctl_proto_depIdxs,
		MessageInfos:      file_proto_portctl_proto_msgTypes,
	}.Build()
	File_proto_portctl_proto = out.File
	file_proto_portctl_proto_goTypes = nil
	file_proto_portctl_proto_depIdxs = nil
}
